version: "3"

services:
  server:
    container_name: fplbasket
    restart: on-failure
    hostname: server
    build: ./server/
    ports:
      - "3636:3636"
    networks:
      - mongo_mongo
      - redis_redis

networks:
  mongo_mongo:
    external: true
  redis_redis:
    external: true
